""" initial db migrations

Revision ID: 31ccedb044e6
Revises: 208daf00a425
Create Date: 2025-10-17 14:05:41.897318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ccedb044e6'
down_revision = '208daf00a425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultant_enquiry', sa.Column('qualification_id', sa.UUID(), nullable=True))
    op.add_column('consultant_enquiry', sa.Column('verified_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consultant_enquiry', 'qualifications', ['qualification_id'], ['id'])
    op.create_foreign_key(None, 'consultant_enquiry', 'users', ['verified_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultant_enquiry', type_='foreignkey')
    op.drop_constraint(None, 'consultant_enquiry', type_='foreignkey')
    op.drop_column('consultant_enquiry', 'verified_by_id')
    op.drop_column('consultant_enquiry', 'qualification_id')
    # ### end Alembic commands ###
