""" initial db migrations

Revision ID: 79d2b0409330
Revises: d71a026c0119
Create Date: 2025-10-16 17:42:00.749982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d2b0409330'
down_revision = 'd71a026c0119'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_name'), 'qualifications', ['name'], unique=True)
    op.create_table('consultant_enquiry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('license_id', sa.Text(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultant_enquiry_email'), 'consultant_enquiry', ['email'], unique=False)
    op.create_index(op.f('ix_consultant_enquiry_full_name'), 'consultant_enquiry', ['full_name'], unique=False)
    op.create_index(op.f('ix_consultant_enquiry_phone'), 'consultant_enquiry', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultant_enquiry_phone'), table_name='consultant_enquiry')
    op.drop_index(op.f('ix_consultant_enquiry_full_name'), table_name='consultant_enquiry')
    op.drop_index(op.f('ix_consultant_enquiry_email'), table_name='consultant_enquiry')
    op.drop_table('consultant_enquiry')
    op.drop_index(op.f('ix_qualifications_name'), table_name='qualifications')
    op.drop_table('qualifications')
    # ### end Alembic commands ###
