""" initial db migrations

Revision ID: 7d86cfd0ea9d
Revises: 31ccedb044e6
Create Date: 2025-10-17 14:43:49.350936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d86cfd0ea9d'
down_revision = '31ccedb044e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
