""" initial db migrations

Revision ID: a357054b031c
Revises: 79d2b0409330
Create Date: 2025-10-17 09:46:37.094960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a357054b031c'
down_revision = '79d2b0409330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
