""" initial db migrations

Revision ID: d71a026c0119
Revises: 6204c48f50c5
Create Date: 2025-10-16 17:39:30.427216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71a026c0119'
down_revision = '6204c48f50c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
